baseurl = ""
title = "Mainroad"
languageCode = "ru"
theme = 'mainroad'
paginate = "10"

[Author] # Used in authorbox
  name = "Волков Илья"
  bio = "Кандидат технических наук. Руководитель проектов."
  avatar = "content/images/avatar.jpg"
